- tests/test_styles/test_style_blank.py
- tests/test_styles/test_style_custom.py
- tests/test_styles/test_style_modern.py
- tests/test_styles/test_style_unknown.py
Thanks for contributing this library.  We're exploring using it for some work on the Open Network Automation Platform (ONAP). 
While attempting to run the test suite on my machine using tox, the first test_styles test case would pass, but then all subsequent test cases would fail.   I discovered the the css files associated with the StandaloneHTMLBuilder were not being reset between tests.  
I made the following tweak as a workaround and they are now passing.
> Fix failing test_styles tests.

- docs/changelog.rst
- docs/conf.py
- setup.py
- sphinxcontrib/needs/directives/need.py
This resolves two hot spots.  
The major one was in the add_sections code that I added.  This had terrible performance for larger documents as it was rendering each multiple times for every need in order to extract the titles.  With this fix, we only render only a single child node to get the section title.  This was taking 5+ minutes on a sample doc, and I dropped it to ~20s.  
I also fixed another hotspot in the ``need.process_need_nodes`` method.  This was an n^2 algorithm that was going through all needs twice in a nested loop to establish the link_backs.  I replaced it with a single pass through the needs, and then just a dict lookup to the part need to update ``links_back``.  In my sample doc, this dropped the time spent in this method from 4.2s to 0.014s.
If you're good with these …
> Fixes #63. Removing two hot spot performance issues related to adding sections and setting the link_backs.

- docs/filter.rst
- sphinxcontrib/needs/directives/needfilter.py
- sphinxcontrib/needs/directives/needflow.py
- sphinxcontrib/needs/directives/needlist.py
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/filter_common.py
I was working on a project where we wanted to sort needs in a table by a `priority` attribute, but the library only supported sorting by `id` or `status` as far as we could tell. This pull request enables sorting on any alphanumeric attribute. It also removes sorting code that was duplicated between the files `filter_common.py` and `needtable.py` and friends.
> Enable sorting on arbitrary numerical attributes

- docs/changelog.rst
- docs/layout_styles.rst
- sphinxcontrib/needs/layout.py
I added a new parameter `exclude` to the layout function `meta_links_all`. Usecase is to have all links documented excluding an unwanted subset.
Documentation and release notes got also updated.
> Add parameter exclude parameter to meta_links_all

- docs/changelog.rst
- sphinxcontrib/needs/layout.py
`meta_all` never had the links as part of its output. This was due to the fact that the `INTERNALS` variables was assigned to the local variable `default_excludes`. `exclude` was then assigned to  `default_excludes` and got modified later. As only references got passed here, the original `INTERNALS` variable got changed on every call to `meta_all` function which led to a couple of hundred entries.
Now the `INTERNALS` variable gets copied using  `INTERNALS.copy()` so a new list instance gets created.
I tested locally and it works now. Also the `no_links` option works now.
Changelog also got updated with the bugfix.
> Bugfix in meta_all for unwanted updates to INTERNALS global variable

- .gitignore
.venv is one of the default local virtual environment names
.envrc is the default direnv configuration
> Added .venv and .envrc to gitignore

- sphinxcontrib/needs/directives/needextract.py
- sphinxcontrib/needs/directives/needfilter.py
- sphinxcontrib/needs/directives/needflow.py
- sphinxcontrib/needs/directives/needgantt.py
- sphinxcontrib/needs/directives/needlist.py
- sphinxcontrib/needs/directives/needpie.py
- sphinxcontrib/needs/directives/needsequence.py
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/filter_common.py
I noticed most of the urlib imports are unused. Also there are two different 'flavours' of `urlparse` used in different places.
> tidy 'urlparse' imports

- docs/conf.py
- docs/directives/need.rst
- sphinxcontrib/needs/api/configuration.py
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/directives/need.py
- sphinxcontrib/needs/layout.py
- sphinxcontrib/needs/needs.py
- sphinxcontrib/needs/warnings.py
- tests/doc_test/doc_export_id/conf.py
- tests/doc_test/doc_extra_links/conf.py
i'm refactored the configuration in the setup function, and a few places where that configuration is consumed.
There's a lot of checking attributes and types throughout, which is unnecessary since the sphinx application API ensures config values are present, have defaults, and are the correct type. there's no need to do this again.
i've also removed a `global` parameter ("NEEDS_FUNCTIONS_CONF"). It didn't seem to be doing anything, and global variables are almost never what you want
> Refactor configuration

- docs/changelog.rst
- docs/directives/needimport.rst
- setup.py
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/directives/needimport.py
* extra options and links are imported
* pre/post/template can be defined by needimport
* same for style and layout
Fixes #227
> needimport supports extra options and links

- .readthedocs.yml
- docs/changelog.rst
- docs/requirements.txt
- poetry.lock
- pyproject.toml
Config so that ReadTheDocs support our new poetry setup.
Working docs of this branch: https://sphinxcontrib-needs.readthedocs.io/en/doc_fix/
> Doc fix: Adding requirement file

- docs/changelog.rst
- sphinxcontrib/needs/filter_common.py
This respects need_parts much better, as "id"
does not contain the need_part sub-id.
Fixes #156
> Using id_complete in filters instead of id only

- sphinxcontrib/needs/directives/needextend.py
- sphinxcontrib/needs/needs.py
- tests/doc_test/doc_needextend/index.rst
- tests/doc_test/doc_needextend/page_1.rst
- tests/doc_test/doc_needextend/page_2.rst
- tests/test_needextend.py
Add needextend directives get now handled
once and all together, before any final
need print out starts.
So no doctree.traverse() is used, except for
removing needextend-node from doctree.
Fixes #310
> Better needextend calling logic

- docs/changelog.rst
- docs/configuration.rst
- sphinxcontrib/needs/builder.py
- sphinxcontrib/needs/external_needs.py
- sphinxcontrib/needs/needs.py
- tests/doc_test/external_doc/conf.py
* config needs_builder_filter added to allow the
defintion of a filter to be used before needs
export starts.
* json_path added to needs_external_needs
Fixes #342, #339
> Adds needs_builder_filter option

- docs/changelog.rst
- docs/configuration.rst
- sphinxcontrib/needs/css/common.css
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/layout.py
- sphinxcontrib/needs/needs.py
> Adds "needs_table_classe" config option

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- Makefile
- docs/conf.py
- docs/contributing.rst
- noxfile.py
- poetry.lock
- pyproject.toml
using pre-commit has some advantages
- you *can't* commit code to the repo doesn't meet your quality gates (unless you use git's `--no-verify` flag)
- there are numerous hooks available for improving quality
- dependencies are installed in an isolated environment
that last point is especially important for this project, as its dependency resolution seems quite brittle
> migrate to pre-commit for linting+formatting

- AUTHORS
- docs/changelog.rst
- sphinxcontrib/needs/utils.py
- tests/test_needs_filter_data.py
While using Sphinx-Needs with a [rinohtype](https://github.com/brechtm/rinohtype)-based builder I discovered that links in needtables did not link properly inside the generated PDF while links in need definitions did. It seems this is caused by references in needtables being created without the `internal=True` attribute which is added to most other references automatically becuase they are created using the `make_refnode` utility ([defined here](https://github.com/sphinx-doc/sphinx/blob/31eba1a76dd485dc633cae48227b46879eda5df4/sphinx/util/nodes.py#L552)).
This change simply adds the `internal=True` attribute to needtable references if they are not marked as external. This means that needtables will build properly with the rinohtype builder (and possibly other builders which rely on the …
> Fix references in needtables when building with rinohtype

- .pre-commit-config.yaml
- pyproject.toml
- sphinxcontrib/needs/builder.py
- sphinxcontrib/needs/config.py
this pull request sets up mypy to allow for incremental adoption of type annotations.
it does this by adding a 'mypy' pre-commit hook, and a 'whitelist' to the `pyproject.toml` file such that all the existing errors are ignored. Over time, this whitelist can be reduced as modules are incrementally 'typed'. New modules should be fully-typed.
> set up mypy hook for incremental adoption

- .github/workflows/ci.yaml
- .github/workflows/docs.yaml
changes the 'links check' job to only trigger if there are changes in the `docs/` directory.
This won't pass while this is an 'expected' check
> only run 'links check' job if docs/ is changed

- .pre-commit-config.yaml
I noticed that the poetry lock file was not quite aligned with the pyproject.toml file.
This PR fixes that misalignment, and adds a pre-commit hook to prevent it from happening again
> fix poetry lock file

- docs/directives/needextend.rst
- docs/filter.rst
resolves useblocks/sphinxcontrib-needs#313
@danwos: I also documented the "docname" option now, as the use case will often require using it. Needextend was also prominently missing from the "list of directives that support filters" ;-)
> Add docu for needextend default option values

- .github/workflows/ci.yaml
fixes the CI failures due to `virtualenv` installing an outdated version of `pip`
> fix lint job by updating pip in virtualenv

- docs/changelog.rst
- docs/configuration.rst
sanity check on formatting. my buildprocess is breaking on
```
.venv/lib/python3.10/site-packages/sphinx_immaterial/object_toc.py", line 33, in _make_section_from_desc
for child in source._traverse():
AttributeError: 'desc' object has no attribute '_traverse'
```
can't check myself
> updated changelog

- pyproject.toml
- sphinx_needs/lsp/esbonio.py
- sphinx_needs/lsp/needs_store.py
CAUTION: this is untested.
- addresses type errors using `namespace-packages` mypy flag
- fix type errors (`self.rst.app.confdir` is an error, since `rst` has no attribute `app`)
- use `pathlib.Path` to represent paths, rather than using strings
> fix type errors in lsp.esbonio

- .pre-commit-config.yaml
Hi @danwos there's a pre-commit hook to ensure that the lock file stays up to date with the pyproject.toml file. One of the recent commits has failed to keep the lock file up to date, which is why the CI is failing on a few PRs.
This PR fixes that. If you merge this and rebase, the PRs should be good again
EDIT: scratch that. it's due to different versions of Poetry locally and in CI. I'll just remove this check instead
> update poetry.lock file

- docs/layout_styles.rst
Instead of using `app.add_css_files` the better way seems to use `html_css_files` cause the files will be added **after** the extension css files by default.
Fix for #743
> [#743] update documentation for custom css files

- sphinx_needs/directives/needflow.py
Template initialisation was done for each need in the result list, which is uneccessary as the tempalte does not change. It's only needs to be rerenderd.
Fixes #760
> Performance fix for needflow

- sphinx_needs/utils.py
With the current implementation, `import_prefix_link_edit` always tries to set a prefix for external needs, even when no prefix is configured for them.
This leads to unnecessary performance problems, especially if the imported needs file is large.
This PR fixes the issue by checking if a `id_prefix` is set first.
> needs_external_needs: Skip setting prefixes if no prefix was given

- .github/workflows/docker.yaml
- docs/changelog.rst
- docs/conf.py
- pyproject.toml
- sphinx_needs/needs.py
Following up on the question in https://github.com/useblocks/sphinx-needs/pull/848#issuecomment-1400210226:
It looks like there are some nice CI pipelines for automatically releasing to PyPI, so perhaps something like this is sufficient to make small patch release?
> Attempt to prepare a 1.2.0 release

- sphinx_needs/needs.py
In my project we are using incremental builds and building often in parallel with `sphinx-build -j auto`. We use sphinx-needs a lot and we've noticed in this configuration huge memory usage during compilation, sometimes so high (30+ GB) that it crashes my laptop. After some debugging, it turns out it comes from the size of the pickled environment that's used to store information between incremental builds.
This file is typically found in your build directory as `environment.pickle`. The problem is that it grows after every incremental parallel build. This can be seen by rebuilding our project with something like:
```sh
grep -Rl "\.\. need" | xargs touch
sphinx-build -j auto [...]
```
When doing this, we notice that the file size of `environment.pickle` increases every time. Of course when …
> Fix unbounded memory usage in pickle environment

- AUTHORS
- sphinx_needs/services/github.py
This solves:
https://github.com/useblocks/sphinx-needs/issues/903
> Guard against "None" body from Github

- sphinx_needs/api/need.py
- tests/test_doc_build_latex.py
Inside the LaTeX generator, it looks for the attributes ids and refid for creating link targets.  When a new layer with a <container> wrapper was added in commit e51fc1f, for an unknown reason this triggered these additional IDs to generate links within the LaTeX output.
A test case has been added to ensure only one hyperref within LaTeX is encountered as well.
(https://github.com/useblocks/sphinx-needs/issues/808)
> needs: Remove some of the extra IDs in the output

- AUTHORS
- docs/changelog.rst
- sphinx_needs/layout.py
As discussed in #967, `build_need` (called from `print_need_nodes`) is currently taking a large amount of build times.
A key reason for this is that the initialisation of the inline parser, which requires compiling numerous regexes, is being run on every call.
This is not required, since the initialisation is invariant.
In this PR therefore, we move the initialisation to a cached function, which will only run once per build.
As shown when using `phinx-analysis  --project needs --pyinstrument --tree --tree-filter 0.01`, compared to #967, this significantly reduces the `print_need_nodes` component of the build time; from taking ~25% to ~8%
In this example it reduces the total build time from ~1.6 seconds to ~1.2 seconds
> 👌 Performance: Memoize Inline parser for `build_need`

- docs/changelog.rst
- sphinx_needs/builder.py
Changing the format from `json` to `needs` will make it more specific to target the `NeedsBuilder`, and any derivatives such as in #960, #961, #962
The `format` attribute of the sphinx builder is perhaps a bit misleading, since it is mainly used to target a "class" of builders, rather than a specific output format,
see: https://www.sphinx-doc.org/en/master/usage/builders/index.html
This will allow for logic in other parts of the sphinx-needs pipeline, e.g. to skip certain build steps not required by the needs builders.
> ♻️ Change `NeedsBuilder` format to `needs`

- docs/conf.py
There should be no reason why a non-headless JVM is ever required
and, without it, sphinx builds are slower and constantly switch window focus
> 📚 DOCS: Always use headless plantuml

- sphinx_needs/directives/needgantt.py
In plantuml V1.2022.12 (23 Oct, 2022), it became a syntax error not to use `@startgantt`: https://plantuml.com/changes
fixes #977
> 🐛 Fix gantt chart rendering

- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needuml.py
This commit adds source origin  information to plantuml nodes, so that they can be reported by Sphinx warnings (for example if the render fails).
For example from #974, this now reports:
```
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:20: WARNING: error while running plantuml
```
rather than just:
```
WARNING: error while running plantuml
```
Note, that this change also requires https://github.com/sphinx-contrib/plantuml/pull/79, to actually emit the source positions during sphinx builds
> 👌 Improve plantuml warnings

- sphinx_needs/functions/functions.py
Needs functions were being parsed the sphinx `env`, as opposed to the required sphinx `app`, as the first argument.
Note, this is good example of where better type annotating and checking would be very beneficial 😅
> 🐛 Fix execute_func

- sphinx_needs/api/configuration.py
- sphinx_needs/api/need.py
- sphinx_needs/config.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/needs.py
- sphinx_needs/services/manager.py
- sphinx_needs/warnings.py
This commit makes `NEEDS_CONFIG` specific to the actual data that it holds, rather than just a generic data store.
---
Note, I have a feeling that this should be replaced entirely, since I'm not a big fan of mutable global variables.
But, for now, this does not change in any way the logic of sphinx-needs
> 🔧 Make `NEEDS_CONFIG` type safe

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- pyproject.toml
- sphinx_needs/directives/list2need.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/directives/needservice.py
- sphinx_needs/nodes/__init__.py
This makes it easier to run pre-commit in isolation, with no system dependencies other than pre-commit itself.
It also means in principle we can set up https://pre-commit.ci/
> 🔧 Make mypy pre-commit hook isolated

- sphinx_needs/api/need.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needimport.py
@danwos unless I am missing something (?) I think this is broken, since `getattr` is used on a dictionary, instead of `dict.get`, so they will always return the default `None`.
Also improved efficiency, by using `json.load` instead of `json.loads`, and not recreating the `known_options` list within a loop
> 🐛 FIX: `NeedImport` logic

- sphinx_needs/layout.py
Previously the logic was mistakenly looping over every character of the string, and so creating a `Text` node per character, rather than a single `Text` node for the full title string.
> 🐛 Fix creation of need title nodes

- docs/contributing.rst
This commit adds a section in the contributing documentation, to outline the logic of the extension, in relation to what events it adds to the sphinx build.
Hopefully, this can help contributers to understand how the extension works, and how/where to suggest fixes/improvements in the code base
> 📚 DOCS: Add outline of extension logic

- docs/configuration.rst
- docs/contributing.rst
- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/directives/need.py
- sphinx_needs/needs.py
Whilst writing #1012, I realised my fix in #995 could be improved, to occur earlier in the build process.
This commit removes the current logic and moves it to occur directly after the need location has been analysed (i.e. once it is no longer necessary).
> 👌 Improve removal of hidden need nodes

- sphinx_needs/config.py
- sphinx_needs/data.py
- sphinx_needs/need_constraints.py
- sphinx_needs/needs.py
- tests/test_needs_warning.py
- Add deprecation warning for `needs_constraints_failed_color` config option, which is no longer used
- Improve exception messages for missing keys in config options
- Add source location to failing constraints warnings
- Improve docstrings and type annotations for data fields/config options
> 👌 Improve `process_constraints`

- docs/directives/need.rst
This PR fixes [extra links field example](https://sphinx-needs.readthedocs.io/en/latest/directives/need.html#extra-links) in the docs.
Documentation describing [need/req's extra links](https://sphinx-needs.readthedocs.io/en/latest/directives/need.html#extra-links) has an incorrect example - `outgoing` dictionary entry is missing:
```
needs_extra_links = [
{
"option": "blocks",
"incoming": "is blocked by",
},
{
"option": "tests",
"incoming": "is tested by",
"copy": False,
"color": "#00AA00"
}
]
```
When used it causes this error:
```
Extension error (sphinx_needs.directives.need):
Handler <function process_need_nodes at 0x7f5d5123e9e0> for event 'doctree-resolved' threw an exception (exception: 'outgoing')
```
Documentation of `needs_extra_links` …
> Fixed extra links example

- sphinx_needs/api/need.py
- sphinx_needs/builder.py
- sphinx_needs/diagrams_common.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needservice.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/directives/needuml.py
- sphinx_needs/environment.py
- sphinx_needs/layout.py
- sphinx_needs/roles/need_count.py
- sphinx_needs/roles/need_func.py
- sphinx_needs/roles/need_incoming.py
- sphinx_needs/roles/need_outgoing.py
- sphinx_needs/roles/need_part.py
- sphinx_needs/roles/need_ref.py
- sphinx_needs/utils.py
- sphinx_needs/warnings.py
- tests/test_needs_id_builder.py
This run-time null check is effectively now replaced by the static type-checking.
> 🔧 Remove `unwrap` function

- tests/__snapshots__/test_basic_doc/test_build_html_parallel[test_app0].doctree.xml
- tests/conftest.py
- tests/doc_test/doc_basic/index.rst
- tests/test_basic_doc.py
This adds some snapshot testing for cached doctrees of a sphinx build, with the `snapshot_doctree` fixture.
(only one has been added currently, as proof of principle, more can be added in the future)
> 🧪 Add snapshot testing for cached doctrees

- docs/changelog.rst
- sphinx_needs/directives/needextend.py
Instead of using `filter_needs()` for a single need (`id == ""XY`) , the need is taken directly from `all_needs`, so that we do not need to perform any filtering.
> 👌 Optimize needextend filter_needs usage

- docs/contributing.rst
- sphinx_needs/data.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/functions/functions.py
- sphinx_needs/need_constraints.py
- sphinx_needs/needs.py
This PR is a step towards #1018, and being able to generate the `needs.json` without running the Sphinx `BUILD` phase.
Here we consolidate all functions that post-process the needs data, after it has been fully extracted from all documents and external sources.
We remove the individual logic from within these functions, to check if the post-processing has already been done, and instead check before running all the functions.
This refactor does not actually change the sphinx-needs process in any way, this will come in later PRs
> 🔧 Consolidate needs data post-processing

- sphinx_needs/api/need.py
- sphinx_needs/builder.py
- sphinx_needs/config.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needuml.py
- sphinx_needs/filter_common.py
- sphinx_needs/functions/common.py
- sphinx_needs/functions/functions.py
- sphinx_needs/need_constraints.py
- sphinx_needs/roles/need_count.py
- sphinx_needs/warnings.py
This PR refactors the functions that post-process needs data, to only get passed what they actually require (rather than just `app` or `env`).
This makes it clearer what they are doing, and in all cases except `resolve_dynamic_values` effectively de-couples the post-processing from Sphinx, since you just need to pass them the needs data and needs configuration.
> ♻️ Refactor needs post-processing function signatures

- AUTHORS
- sphinx_needs/layout.py
- tests/doc_test/doc_layout/conf.py
- tests/doc_test/doc_layout/index.rst
- tests/test_layouts.py
The usage of the `prefix` parameter of the `meta` layout function (as per the docs) does not work. There are two problems with this:
1. The documentation for `meta` does not mention that backslashes need to be escaped and shows unescaped backslashes instead. The docs for `meta_all` do not make this mistake.
2. [Since version 0.16](https://docutils.sourceforge.io/HISTORY.html#release-0-16-2020-01-16), docutils inserts null-characters when parsing escaped backslashes, which in turn is not accepted by [`ast.parse`](https://docs.python.org/3/library/ast.html#ast.parse). The solution is described in the [release notes for docutils 0.16](https://docutils.sourceforge.io/HISTORY.html#release-0-16-2020-01-16): Using `node.astext()` instead of `str(node)`
> Fix usage of reST syntax in prefix parameter of meta

- sphinx_needs/needsfile.py
- tests/__snapshots__/test_basic_doc.ambr
- tests/__snapshots__/test_export_id.ambr
- tests/__snapshots__/test_external.ambr
- tests/__snapshots__/test_import.ambr
- tests/__snapshots__/test_need_constraints.ambr
- tests/__snapshots__/test_needextend.ambr
- tests/__snapshots__/test_needs_builder.ambr
Remove additional keys from the `needs.json`, that are not intended to be exposed to the user:
- back links for user defined link types (standard back links are already ommited),
- `id_parent` and `id_complete`, which are only relevant to parts expansion.
(Note, this is relevant for #957)
> 👌 Remove some unnecessary keys from `needs.json`

- .github/workflows/ci.yaml
This job simply passes if all other jobs pass.
This means that it can be used as a singlular "required" for branch protection rules, rather than having to change every time the test matrix changes
> Add `check` CI job

- .github/workflows/ci.yaml
This was added in #1051, but given that this CI job skips all JS tests, its pointless to have it here
> Remove node install from core tests CI

- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/utils.py
Just de-duplicates some logic used in multiple places
> 🔧 Add `remove_node_from_tree` utility function

- .github/workflows/ci.yaml
- README.rst
- docs/conf.py
- docs/installation.rst
- noxfile.py
- poetry.lock
- pyproject.toml
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/utils.py
- tests/doc_test/doc_needbar/conf.py
- tests/doc_test/doc_needbar/index.rst
- tests/no_mpl_tests.py
- tests/test_needbar.py
This PR supercedes #493
It makes matplotlib and numpy optional dependencies, using `pip install sphinx-needs[plotting]`, by:
1. Removing direct uses of numpy
2. Moving the matplotlib import to a function, which can return `None`
3. Handling the `None` case in the `needbar`/`needpie` post-processing, by emmiting a warning and replacing the nodes with error admonitions.
A seperate test job and related test file is added for testing builds with needbar/needpie directives, when matplotlib is uninstalled.
> ♻️ Make matplotlib dependency optional

- .pre-commit-config.yaml
- README.rst
The v2.0.0 failed to publish 🙈, see https://github.com/useblocks/sphinx-needs/actions/runs/6851896295/job/18629213955
I believe this should be the fix.
Not sure if there is any better way to pre-check the deployment?
> 🧪 Test README builds in pre-commit

- .github/workflows/docker.yaml
- docker/Dockerfile
Fix the Docker build, which failed on the last deployment
Also 
- Add the new `plotting` extra, to install `matplotlib`
- Makes the docker build workflow run (without deployment) in PRs that modify the Docker files,
- fixes deprecation warning in workflow: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> 🔧 Fix Docker deployment

- .github/workflows/ci.yaml
This is mainly because it is required by codecov, for comparing coverage of PRs
> 🧪 Run CI also on pushes to master

- sphinx_needs/templates/permalink.html
- added text to display while loading the content.
Currently on bigger projects it takes considerable amount of time to load the location of the selected ID. During that time currently there is a blank page shown to the user.
This change will display a static text: `Searching, Please Wait...`
> Update permalink.html with a frienly text

- docs/filter.rst
- pyproject.toml
- sphinx_needs/data.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/directives/utils.py
- sphinx_needs/filter_common.py
- tests/doc_test/filter_doc/conf.py
- tests/doc_test/filter_doc/filter.css
- tests/doc_test/filter_doc/filter_no_needs.rst
- tests/doc_test/filter_doc/index.rst
- tests/test_filter.py
Add option `:filter_warning:` to directives (e.g. needtable) to show no text or given text instead of the default text.
> #947 filter_warning option to replace default "No needs passed the filters" text

- docs/conf.py
- docs/directives/needreport.rst
- sphinx_needs/directives/needreport.py
- sphinx_needs/directives/needreport_template.rst
- tests/doc_test/doc_needreport/conf.py
- tests/doc_test/doc_needreport/index.rst
- tests/test_needreport.py
Currently there is no test for this directive, this PR adds one.
This PR also fixes the directive:
- Make the options flags
- Change errors in the directive to emit warnings, rather than excepting the whole build
- Allow for `template` to be specified as a directive option
- Allow the the `dropdown` directive used in the default template, which requires an external sphinx extension, to be overriden using `needs_render_context = {"report_directive": "admonition"}` (I left the default as `dropdown`, so as not to introduce a breaking change)
> 🧪 Add test for `needreport` directive

- sphinx_needs/directives/need.py
- sphinx_needs/roles/need_outgoing.py
- sphinx_needs/roles/need_ref.py
- sphinx_needs/utils.py
Ensure the splitting of a need ID, on a `.` into `main.part` IDs, cannot except (and remove duplication of the logic)
closes #1096
> 🐛 FIX: Centralise splitting of need ID

- sphinx_needs/defaults.py
- tests/doc_test/doc_needtable/conf.py
- tests/doc_test/doc_needtable/test_titles.rst
- tests/test_needtable.py
For `key as "title"` columns, the regex has been changed, to allow for the key to contain anything except whitespace characters, and the title to contain anything except the `"` character
closes #1089
> 👌 Make needtable titles more permissive

- docs/conf.py
- docs/configuration.rst
- sphinx_needs/config.py
- sphinx_needs/directives/need.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_outgoing.py
- sphinx_needs/roles/need_ref.py
- tests/conftest.py
- tests/doc_test/doc_report_dead_links_false/conf.py
- tests/test_basic_doc.py
- tests/test_broken_links.py
- tests/test_github_issues.py
- tests/test_needs_external_needs_build.py
- tests/test_report_dead_links.py
Currently, warnings for need outgoing links that reference a non-existent ID, are only generated "indirectly" in the render phase; where  `NeedOutgoing` nodes are converted to nodes that are understood by sphinx builders (HTML, PDF, ...).
Since this render phase is no longer needed/run for simply creating the `needs.json`, using the `needs` builder, these warnings are not generated.
Additionally, any needs that are not explicitly rendered in the documentation, like externally imported needs, are also skipped.
The reporting of unknown links is now moved to the `check_links` function, meaning it is now run for all needs and all builders. The warnings have also been given a subtype `link_outgoing` or `external_link_outgoing`, e.g.
```
srcdir/index.rst:12: WARNING: Need 'SP_TOO_002' has …
```
> 🐛👌 Centralise need missing link reporting

- poetry.lock
- pyproject.toml
- sphinx_needs/directives/needservice.py
- sphinx_needs/services/base.py
- sphinx_needs/services/github.py
- sphinx_needs/services/open_needs.py
- tests/__snapshots__/test_service_github.ambr
- tests/benchmarks/test_basic.py
- tests/benchmarks/test_official.py
- tests/doc_test/doc_service_github/conf.py
- tests/doc_test/doc_service_github/index.rst
- tests/test_basic_doc.py
- tests/test_import.py
- tests/test_measure_time.py
- tests/test_needpie.py
- tests/test_needs_external_needs_build.py
- tests/test_open_needs_service.py
- tests/test_service_github.py
- tests/test_services/test_service_basics.py
- tests/test_styles/test_style_css_js_registration.py
By codecov, this directive was completely untested in the current test suite, so I added a test and also improved some other things I noticed:
- remove duplication of request mocking solutions in the test-suite ([responses](https://github.com/getsentry/responses) is more popular than [requests-mock](https://github.com/jamielennox/requests-mock))
- remove superfluous requests mocking in basic docs tests (that do not make any requests)
- add test for github `needservice` directives
- replace raising`NeedGithubServiceException` with emitting `needs.github` warnings
- pass the directive to the `service.request` method (in a non-breaking manner) so that it can be used to add the directive source location to the warnings
- Replace remaining tests that used `Sphinx` with `SphinxTestApp`, which …
> 👌 Improve and test github `needservice` directive

- docs/conf.py
- pyproject.toml
- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/directives/need.py
Note, I have made changes in a way to not breaking any existing logic / tests.
However, I've added a number of TODOs where I have "ignored" type incompatibilities that do look like they should be resolved.
For example, `add_external_need`, understandably sets `docname`/`lineno` to `None`, however, some parts of the code base appear to not account for this possibility.
Anyway, I'll look into these in later PRs
> 🔧 Enforce type checking in `api/need.py`

- sphinx_needs/api/need.py
- sphinx_needs/config.py
Explain what are the different values it can have
> 🔧 Add better typing for `global_options` config variable

- sphinx_needs/data.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/external_needs.py
- sphinx_needs/needs.py
`constraints` is a core sphinx-need option, and so it is not necessary to add it to the `extra_options`
(this change was made as a result of #1122)
> 🔧  Remove `constraints` from `extra_options`

- sphinx_needs/config.py
- sphinx_needs/data.py
- sphinx_needs/defaults.py
- sphinx_needs/directives/need.py
- sphinx_needs/needs.py
As discussed in https://github.com/useblocks/sphinx-needs/issues/1122#issuecomment-1958004054,
These fields are used by `needgantt` but their name can be configured by `needs_duration_option` and `needs_completion_option`.
So here we remove the hard-coding and dynamically use these configuration options to set what option/key names are added.
> 👌 Remove hard-coding of `completion` and `duration` need fields

- sphinx_needs/api/need.py
- sphinx_needs/builder.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/filter_common.py
- sphinx_needs/functions/common.py
- sphinx_needs/roles/need_count.py
- sphinx_needs/warnings.py
- tests/doc_test/filter_doc/filter_all.rst
- tests/doc_test/filter_doc/filter_no_needs.rst
- tests/doc_test/filter_doc/filter_search.rst
- tests/doc_test/filter_doc/filter_tags_or.rst
- tests/doc_test/filter_doc/index.rst
- tests/test_filter.py
See `tests/test_filter.py`,  e.g.
```
srcdir/index.rst:51: WARNING: Filter 'xxx' not valid. Error: name 'xxx' is not defined. [needs.filter]
```
> 👌 Improve warnings for invalid filters (add source location and subtype)

- docs/configuration.rst
- docs/dynamic_functions.rst
- sphinx_needs/layout.py
- sphinx_needs/needsfile.py
- sphinx_needs/utils.py
- tests/doc_test/add_sections/conf.py
- tests/doc_test/extra_options/conf.py
- tests/doc_test/import_doc/conf.py
- tests/doc_test/import_doc_empty/conf.py
- tests/doc_test/import_doc_invalid/conf.py
- tests/doc_test/non_exists_file_import/conf.py
These needs fields were removed in v0.5.0
> 🔧 Remove usage of `hide_status` and `hide_tags`

- sphinx_needs/config.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_outgoing.py
- sphinx_needs/utils.py
To detail all possible dict keys
> 🔧 Add better typing for `extra_links` config variable

- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/diagrams_common.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/functions/common.py
- sphinx_needs/layout.py
- sphinx_needs/roles/need_incoming.py
- sphinx_needs/roles/need_outgoing.py
- sphinx_needs/roles/need_part.py
- sphinx_needs/roles/need_ref.py
- sphinx_needs/utils.py
Account for these being `None` for external needs, that have no source mapping within the project
Practically, if `is_external is False` then `docname/lineno` are`str`, but if `is_external is True` then `docname/lineno` are `None`.
This internal relationship is difficult to encode in the type system though.
So here we always account for  `docname is None`, even if we have already checked for `is_external is False`
> 🔧 Fix typing of need docname/lineno

- .github/workflows/ci.yaml
- tests/conftest.py
- tests/test_broken_links.py
- tests/test_filter.py
- tests/test_github_issues.py
- tests/test_report_dead_links.py
- tests/test_service_github.py
In #1067 I added coverage uploads.
@PhilipPartsch has uncovered an issue with this; it appears at least in Windows if `pytest` fails it still progresses to the next command `coverage xml` and then if this runs ok it doesn't mark the job step as failing 🤦
> 🧪 Fix Windows pytest CI runs

- .github/workflows/release.yaml
This failed in the last release and TBH it doesn't make sense to upload to test-pypi on the actual release workflow, because it is too late to test then; 
if we wanted to do this it should be e.g. on every commit to the `master` branch
> 🔧 Remove release to test-pypi

- docs/_static/custom.css
- poetry.lock
- pyproject.toml
- sphinx_needs/css/common/need_core.css
- sphinx_needs/layout.py
- sphinx_needs/libs/html/sphinx_needs_collapse.js
- tests/test_github_issues.py
Currently, the need collapse toggle icons are added to the page like:
Wrapping the SVG icons in an `<img src=...>` is not great, because it does not allow it to be properly styled.
Indeed for our own docs, we have to use the horrible hack of `filter: brightness(0) invert(1)`, to get these icons to have the correct color for light/dark mode 😬 
This PR instead places the entire SVG onto the page, and adds some core CSS to set it at the correct relative size (and float right)
the SVG then matches the local text color, without any need for additional CSS:
Also, the initial visibility of the icons is now set correctly, before any JS is run,
so that you don't get a bad render experience, whereby both icons are initial visible (until the JS is triggered)
Note, it might be ideal to de-duplicate …
> 👌 Improve cross-theme compatibility of need collapse button

- sphinx_needs/api/need.py
- sphinx_needs/config.py
- sphinx_needs/diagrams_common.py
- tests/doc_test/doc_basic/conf.py
Add typing for `needs_types`  items, and allow for the `style` and `color` keys to use defaults when undefined.
> 👌 Better typing for `needs_types` and allow default style/color

- docs/directives/needflow.rst
- sphinx_needs/data.py
- sphinx_needs/directives/needflow.py
- tests/doc_test/doc_needflow/index.rst
- tests/doc_test/doc_needflow/needflow_with_root_id.rst
- tests/test_needflow.py
A classic use-case for visualising a graph, is to select a root node and visualise the sub-tree of all ancestor / decendant nodes.
Here we add the capability to the `needflow` directive, via new `root_id`, `root_direction` and `root_depth` options
> ✨ Allow creating a `needflow` from a `root_id`

- docs/directives/needflow.rst
- sphinx_needs/data.py
- sphinx_needs/directives/needflow.py
The ``:border_color:`` option allows for setting per need border colors, based on the need data.
The value should be written with the variant syntax, and each return value should be a hex (RGB) color.
See: https://sphinx-needs--1194.org.readthedocs.build/en/1194/directives/needflow.html#border-color
> ✨ Add `border_color` option for `needflow`

- sphinx_needs/api/exceptions.py
- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/external_needs.py
- tests/doc_test/parallel_doc/index.rst
- tests/doc_test/parallel_doc/page_5.rst
- tests/test_broken_doc.py
- tests/test_parallel_execution.py
Change duplicate need feedback from raising exceptions to emitting Sphinx warnings, e.g.
```
path/to/page.rst:4: WARNING: A need with ID STORY_PAGE_1 already exists, title: 'duplicate'. [needs.duplicate_id]
```
and ensure warning is also emitted during parallel builds
Note, although there was already a parallel build test in the test suite, 
actually it was not running parallel because there were not enough documents in the test project (see https://github.com/sphinx-doc/sphinx/pull/12796),
so one more is added and now the warning is correct.
> 🐛 fix warnings for duplicate needs in parallel builds

- sphinx_needs/api/need.py
Currently they are silently ignored,
so this commit specifically checks for them and provides a warning. This can then be removed in a future version of sphinx-needs
> 🔧 Deprecate unused `add_need` kwargs

- sphinx_needs/api/configuration.py
- sphinx_needs/config.py
- sphinx_needs/needs.py
- sphinx_needs/services/manager.py
This allows their "origin" to be tracked, and thus to be output as part of a `needs.json` in a later PR
(extracted from #1132)
> 🔧 Store description for each extra need option

- docs/builders.rst
- docs/configuration.rst
- sphinx_needs/config.py
- sphinx_needs/data.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/external_needs.py
- sphinx_needs/needsfile.py
- tests/__snapshots__/test_basic_doc.ambr
- tests/__snapshots__/test_export_id.ambr
- tests/__snapshots__/test_external.ambr
- tests/__snapshots__/test_import.ambr
- tests/__snapshots__/test_need_constraints.ambr
- tests/__snapshots__/test_needextend.ambr
- tests/__snapshots__/test_needs_builder.ambr
- tests/__snapshots__/test_service_github.ambr
- tests/test_external.py
- tests/test_needs_builder.py
Setting `needs_json_remove_defaults=True`,
will now create a `needs.json` with all need fields that have default values removed, and the defaults are specified in the `needs_schema` (recently added in #1230)
In the external/import needs loaders, these are then restored from the `needs_schema`.
In our internal documentation (of 224 needs), this reduces the generated `needs.json`size from 19692 lines / 760kB to 5894 lines / 248kB
Note: Currently, the default is `needs_json_remove_defaults=False`, so as not to be back-breaking yet,
but I would look to eventually change this to `True` before the next "major" release.
> 👌 Add `needs_json_remove_defaults` configuration

- sphinx_needs/needsfile.py
Removing the indent of `json.dump` means it will now be output on a single line; reducing the size of the stored JSON.
Together with #1232, the size for the internal docs ``needs.json`` (224 needs) is reduced from ~750kB to 125kB
Most editors have built-in facilities to "format/expand" JSON, so I think this mitigates any "manual readability", without the need for any additional configuration to control this
> 👌 Minify output of `needs.json`

- sphinx_needs/data.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/directives/needuml.py
- tests/__snapshots__/test_basic_doc/test_build_html_parallel[test_app0].doctree.xml
This PR changes logic for nearly all directives that require post-processing, so that all information coming from the directive is stored directly on the node in the doctree, rather than centrally in the `BuildEnvironment`.
It is unnecessary to store this data centrally and it increases complexity (having to keep it in-sync) and the size of the `BuildEnvironment`.
The only node I have not done this for is `needuml`, since there is some additional interplay between the `arch` need field, which I do not fully understand yet.
> 🔧 Move data from global env to individual nodes

- sphinx_needs/needs.py
It took me an emberassingly long time to figure out what was going on, since I had forgotten that I changed the config. I was searching my .rst files and for some hidden caches ...
> 🔧 Improve `NeedsConfigException` messages (hint how to fix)

- docs/conf.py
- pyproject.toml
- sphinx_needs/data.py
- sphinx_needs/debug.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow/_graphviz.py
- sphinx_needs/directives/needflow/_plantuml.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/filter_common.py
- tests/__snapshots__/test_export_id.ambr
- tests/test_export_id.py
This PR adds capturing of origin location and runtimes of each call to `process_filters`.
For `needs_debug_measurement=True` it also outputs this data to `<outdir>/debug_filters.json`, and
prints the 10 longest running filters to stdout, e.g. for the internal docs build:
```
Slowest need filters:
/Users/chrisjsewell/GitHub/sphinx-needs/docs/filter.rst:282: 0.003848s (needlist)
/Users/chrisjsewell/GitHub/sphinx-needs/docs/services/github.rst:276: 0.001176s (needtable)
/Users/chrisjsewell/GitHub/sphinx-needs/docs/directives/needtable.rst:156: 0.000704s (needtable)
/Users/chrisjsewell/GitHub/sphinx-needs/docs/directives/needextract.rst:20: 0.000687s (needextract)
/Users/chrisjsewell/GitHub/sphinx-needs/docs/directives/needflow.rst:14: 0.000639s (needflow) …
```
> ✨ Capture filter processing times

- sphinx_needs/needsfile.py
This mistakenly contains a set of keys related to `NeedsInfoType`, not `NeedsFilterType`, and there should be no reason to exclude any keys from `NeedsFilterType`
> 🔧 Remove `NeedList.JSON_KEY_EXCLUSIONS_FILTERS`

- sphinx_needs/directives/needextract.py
- sphinx_needs/layout.py
The `create_need` function name/location was misleading, in that its only use is actually for building `needextract` representations. Therefore, we move it into the `needextract` module.
(extracted from #1198, so we can make it clearer what the changes are to the code, rather than what is just moved code)
> 🔧 Move `layout.create_need` to `needextract._build_needextract`

- docs/directives/needextract.rst
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/layout.py
Rendering of `needextract` nodes had two key issues:
1. The call to `BuildEnvironment.resolve_references` was already converting the need node to its final representation (since the calls `process_need_nodes`), and so the later call to `build_need` didn't do anything.
This is why the requested layout was not being created.
2. A `needextract` can generate multiple need representation, but all of them were being given the same `id` of the original `NeedExtract` node.
All nodes are now wrapped in a containing node, that is set with this `id`
Additionally, warnings are now emitted for unfound needs, rather than raise exceptions
Also, `build_need` is renamed to `build_need_repr`, to better describe its purpose, and its signature is slightly changed, to allow for the new logic.
For examples of …
> 🐛 Fix rendering of `needextract` needs

- sphinx_needs/warnings.py
- tests/test_needs_warning.py
- remove "fix" that is now fixed in sphinx (https://github.com/sphinx-doc/sphinx/commit/6065ab676c08fe37b84bfd0a0146ab08754c8b92)
- add subtype to to warnings
- improve test to check entire warning string
> 👌 Improve need warnings

- .github/workflows/release.yaml
build and publish in one go, rather than having to use upload/download between two jobs
> 🔧 Fix release job

- sphinx_needs/directives/needpie.py
- sphinx_needs/filter_common.py
- sphinx_needs/utils.py
- tests/doc_test/doc_needs_filter_data/filter_code.rst
- tests/doc_test/doc_needs_filter_data/index.rst
- tests/test_needs_filter_data.py
Currently malformed filter function strings would simply be ignored, and thus the results would not be filtered,
which is especially bad if you have a large amount of needs.
This PR provides a warning for all malformed `filter-func` values, and also returns the result as an empty list of needs,
so we do not wasted time processing them.
A test is also added
> 🐛 Handle malformed `filter-func` option value

- sphinx_needs/filter_common.py
We only need to perform the sorting (which could be slow for large amounts of needs) on the filtered needs, rather than all the needs.
> 👌 Move sorting to end of `process_filters`

- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/filter_common.py
- sphinx_needs/roles/need_count.py
Rename `prepare_need_list` to `expand_needs_view`, to make its purpose clearer,
and change its input argument to a `NeedsView`, so we can do the expansion more performantly.
> 🔧 change `prepare_need_list` to `expand_needs_view` function

- sphinx_needs/api/need.py
- tests/test_utils.py
For need directive options of the format e.g. `:tags: a,[[func()]],b`
Consolidate into single conversion function and add unit test
fixes #1271
> 👌 Improve parsing of need option lists with dynamic functions

- sphinx_needs/functions/common.py
- sphinx_needs/functions/functions.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_func.py
- tests/doc_test/doc_dynamic_functions/index.rst
- tests/test_dynamic_functions.py
- tests/test_global_options.py
Currently, the `need_func` role passes a "dummy need" to dynamic functions, which would except for most dynamic functions. So:
1. we replace the dummy need with `None` and ensure dynamic functions account for this input.
2. when a `need_func` is used within a need directive, it uses that need as input for the dynamic function, rather than `None`
> 👌 pass parent need to `need_func`

- sphinx_needs/directives/needflow/_graphviz.py
The title for parts is actually taken from their `content` field, not `title`
> 🐛 Fix `needflow` `graphviz` title for parts

- sphinx_needs/directives/needflow/_graphviz.py
- sphinx_needs/directives/needflow/_plantuml.py
In a minor oversight from #1235, I realised that I did not pass the `needs` list to the `highlight` filter, as is the case for the `plantuml` engine.
I also took the opportunity to improve `_plantuml`, by passing the `NeedsView` to the sub-functions, rather than just the values.
> 🐛 Pass `needs` to `highlight` filter of `graphviz` `needflow`

- sphinx_needs/builder.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needuml.py
- sphinx_needs/filter_common.py
- sphinx_needs/functions/common.py
- sphinx_needs/roles/need_count.py
- sphinx_needs/warnings.py
This makes it clearer what representation of needs we are trying to filter (see #1264).
The idea is that eventually we might be able to analyse the filter string and perform "short-circuit" filters,
for example, if it is `id == "abc"` and `filter_needs_view`, then all we actually need to perform is an `O(1)` lookup of the mapping, rather than perform an `O(N)` iteration over all the needs.
This then begins to address #1219.
> 🔧 split `filter_needs` func by needs type

- sphinx_needs/directives/need.py
We need to exhaust the entire `findall` iterator, before performing mutations on the doctree, otherwise this can lead to unexpected results (as has been found in the PACE project)
> 🐛 Fix removal of `Needextend` nodes

- sphinx_needs/config.py
Remove defined configuration variables that are not used anywhere in the codebase. I guess these are legacy configurations that were used once but no more.
> 🔧 Remove unused configuration variables

- docs/directives/needextend.rst
- docs/dynamic_functions.rst
- docs/needs_templates/spec_template.need
- docs/roles.rst
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/functions/common.py
- sphinx_needs/functions/functions.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_func.py
- tests/doc_test/doc_dynamic_functions/index.rst
- tests/doc_test/needextract_with_nested_needs/index.rst
- tests/test_dynamic_functions.py
- tests/test_global_options.py
- tests/test_needextract.py
There are currently two ways to use dynamic functions within need directive's content:
1. ``[[copy("id")]]``; is problematic, because it does not adhere to the rst/myst syntax specification, and has already show to cause issues and be surprising to users (#1263)
2. `` :need_func:`[[copy("id")]]` ``; is better but overly verbose
In this PR, I introduce a new role, which I believe should supersede both: `` :ndf:`copy("id")` `` (open to other suggestions for the name)
Here we take the entire content to be the function, as so do not require the `[[]]`, reducing verbosity and processing
Note, one thing that the role approach cannot do, is to allow placeholders in URLs, e.g. `` `link <http://www.[[copy('id')]]>`_ ``
However, if this is truly required, then I believe we should introduce a new …
> ✨ Add `ndf` role, deprecate `need_func` & `[[...]]` in need content

- docs/api.rst
- docs/conf.py
- docs/filter.rst
- docs/tutorial.rst
- sphinx_needs/api/__init__.py
- sphinx_needs/api/need.py
- sphinx_needs/builder.py
- sphinx_needs/data.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needflow/_graphviz.py
- sphinx_needs/directives/needflow/_plantuml.py
- sphinx_needs/directives/needflow/_shared.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/external_needs.py
- sphinx_needs/filter_common.py
- sphinx_needs/functions/common.py
- sphinx_needs/functions/functions.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_count.py
- sphinx_needs/roles/need_func.py
- sphinx_needs/roles/need_part.py
- sphinx_needs/utils.py
- sphinx_needs/views.py
- sphinx_needs/warnings.py
- tests/test_filter.py
- tests/test_needimport.py
- tests/test_needuml.py
This PR addresses issues in performance scalability of needs filtering:
- In a known user project, with ~40,000 needs, there are 5316 individual filter calls, across directives such as `needarch`, `needtable`, `needpie`, etc. Each takes on average 0.33 seconds, cumulative totalling **1751 seconds**
- Applying this PR reduces the average time to 0.033 seconds, cumulatively totalling **181 seconds**
----
The main issue with filtering (a.k.a. querying) needs, is that it requires looping over every need and executing a Python evaluation of the filter string (e.g. `id == "xxx"`), which scales with `O(N)` time.
To reduce this to `O(1)` time, for common patterns, we look to do two things:
1. More tightly control access to needs data across its lifecycle (see #1264): 
By making needs data …
>  ♻️ Replace need dicts/lists with views (with fast filtering)

- sphinx_needs/data.py
- sphinx_needs/needs.py
- sphinx_needs/warnings.py
- tests/test_needarch.py
- tests/test_needuml.py
- tests/test_open_needs_service.py
- tests/test_services/test_service_basics.py
These attributes should always be accessed via the API interface,
adding `_` to them makes this contract more explicit.
> 🔧 Make direct access to `env` attributes private

- docs/configuration.rst
- docs/filter.rst
- sphinx_needs/config.py
- sphinx_needs/data.py
- sphinx_needs/directives/needuml.py
- tests/test_needarch.py
- tests/test_needuml.py
To guard against long-running `needuml` / `needarch` processing times. In particular, these can occur if the jinja template contains many calls to the filter function.
> 👌 Add `needs_uml_process_max_time` configuration

- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/external_needs.py
- tests/__snapshots__/test_external.ambr
This PR centralises the declaration of what keys to omit from external/import sources, onto the `NeedsCoreFields` spec.
It then also uses `NeedsCoreFields` to identify unknown keys, and emits a warning if any are found.
Note, this could be breaking for existing builds, in that a warning may now be emitted,
but I decided not to put this under a "configuration flag", since users can simply choose to ignore it with `suppress_warnings`
---
One issue that was identified during this is the distinction of `title` vs `full_title`, whereby `title` is meant to be the potentially trimmed version of `full_title`. 
I think storing both fields is unnecessary and confusing; trimming of the title is a presentational issue that should be handled when necessary, not stored in the data.
Also, it is of note …
> 👌 Warn on unknown need keys in external/import sources

- sphinx_needs/directives/needuml.py
- sphinx_needs/roles/need_ref.py
- tests/__snapshots__/test_needuml.ambr
- tests/doc_test/doc_needuml_jinja_func_ref/index.rst
- tests/test_needuml.py
> 👌 Allow `ref` in `neeuml` to handle need parts

- sphinx_needs/directives/needextract.py
> 👌 Improve warning for needextract incompatibility with external needs

- sphinx_needs/directives/needflow/_plantuml.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needsequence.py
`sphinxcontrib.plantuml` is optional, should not be a top-level import
> 🐛 Fix plantuml top-level import

- sphinx_needs/data.py
It should not be necessary to ever show these fields to users on the rendered need
fixes #1329
> 🔧 Remove some internal fields from needs layout

- sphinx_needs/api/configuration.py
- sphinx_needs/api/need.py
- sphinx_needs/config.py
- sphinx_needs/data.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/directives/needreport.py
- sphinx_needs/external_needs.py
- sphinx_needs/functions/__init__.py
- sphinx_needs/functions/functions.py
- sphinx_needs/needs.py
- sphinx_needs/needsfile.py
- sphinx_needs/services/manager.py
- sphinx_needs/utils.py
- sphinx_needs/warnings.py
These three configurations are complicated by the fact that they can be set both in the `conf.py` configuration, but also via functions from `sphinx_needs.api`.
This has lead to confusion, when to use `NEEDS_CONFIG` and when to use `NeedsSphinxConfig`, and indeed I have already had to fix numerous bugs when `NeedsSphinxConfig` was incorrectly used
In this PR we split access to these configs into:
- `NeedsSphinxConfig._extra_options`, `NeedsSphinxConfig._functions`, `NeedsSphinxConfig._warnings`, which access the "raw" sphinx configuration
- `NeedsSphinxConfig.extra_options`, `NeedsSphinxConfig.functions`, `NeedsSphinxConfig.warnings`, which access the "combined" sphinx config + API added values
We also make `NEEDS_CONFIG` private and merge in the use of `NEEDS_FUNCTIONS`.
This makes the …
> ♻️ Improve access to dynamic configs: extra_options, functions, warnings

- docs/configuration.rst
- sphinx_needs/config.py
- sphinx_needs/needs.py
- tests/__snapshots__/test_extra_options.ambr
- tests/doc_test/extra_options/conf.py
- tests/test_extra_options.py
This PR allows for using a dict for a `needs_extra_options` item, that can have both a `name` and (optional) `description` key, e.g.:
```python
needs_extra_options = [
"introduced",
{"name": "impacts", "description": "What is the impact of this need?"},
]
```
---
Note, I envisage this extended dict format eventually also supporting other settings such as a data type, default, and possibly also limiting the need types it applies to, e.g.
```python
needs_extra_options = [
{"name": "duration", 
"description": "What is the impact of this need?",
"type": "number",
"default": 1,
"need_types": ["req", "spec"]
},
]
```
These though would require additional code changes
> ✨ Allow configuring description of extra option

- sphinx_needs/needs.py
Since https://github.com/sphinx-doc/sphinx/pull/12949 it has become more apparent that sphinx detects some sphinx-needs configuration values as changed when they have not. This fixes most of these by merging user defined config with built-in defaults earlier in the processing.
The only thing it does not fix is config altered by adding services.
This is difficult, since services are stored on the `env`, which is not initialised until after the config is checked.
> 🔧 Merge defaults into config earlier

- sphinx_needs/utils.py
- tests/doc_test/doc_needs_filter_data/filter_code.rst
- tests/doc_test/doc_needs_filter_data/module/filter_code_func.py
- tests/test_needs_filter_data.py
I just changed the split of the path of filter-func to split on the first dot starting from the right.
This means anything to the right will be the function name and anything to the left will be the module import path 
This Fix will close the issue #1372
> Allow filter-func in need-pie to have multiple dots in the import path. 

- docs/layout_styles.rst
Caught a couple typos while reading the docs.
1:
Take this line:
```
If you need to customize the css definitions, there are twi ways of doing it:
```
and correct it:
```
If you need to customize the css definitions, there are two ways of doing it:
```
2:
Correct this line:
```
<table class="need needs_grid_simple needs_layout_complex needes_style_blue docutils" id="SPEC_1">
```
to this:
```
<table class="need needs_grid_simple needs_layout_complex needs_style_blue docutils" id="SPEC_1">
```
> Fix typo in layout_styles.rst

- sphinx_needs/external_needs.py
Paths set in the `conf.py` should be relative to it, not to the `srcdir`.
Note, often `confdir` and `srcdir` are equivalent, but this is not always the case.
> 🐛 Fix: make external paths relative to `confdir`, not `srcdir`

- docs/configuration.rst
- docs/directives/needimport.rst
- sphinx_needs/config.py
- sphinx_needs/directives/needimport.py
- tests/doc_test/import_doc/conf.py
- tests/doc_test/import_doc/index.rst
```python
needs_import_keys = {"my_key": "path/to/needs.json"}
```
Allows for the use of:
```restructuredtext
.. needimport:: my_key
```
As discussed with @arwedus
> ✨ Add `needs_import_keys` configuration

- docs/changelog.rst
- docs/dynamic_functions.rst
Fix RST syntax in https://sphinx-needs.readthedocs.io/en/latest/dynamic_functions.html
The linkcheck builder fails with a certain anchor. I removed it and just referred to the issue.
> 📚 Fix markup for dynamic functions

- sphinx_needs/needs.py
Back links are computed at the end of the need post-processing, after `needextend` have been applied.
Back links should always be in-sync with forward links, therefore it doesn't make sense to modify back links in this way.
Thankfully, the current availability of back link options in `needextend` directives is not documented, and so are unlikely to have been actually used.
> ♻️ Remove back link manipulation from `needextend`

- docs/directives/needimport.rst
Explain the difference between local paths that are; relative to the document, relative to the source directory, absolute
see: https://sphinx-needs--1384.org.readthedocs.build/en/1384/directives/needimport.html
> 📚 clarify `needimport` argument format

- docs/directives/needextend.rst
- sphinx_needs/data.py
- sphinx_needs/directives/needextend.py
- tests/doc_test/doc_needextend_unknown_id/index.rst
- tests/test_needextend.py
The argument for `needextend` can refer to either a single need ID or filter function.
Currently, the format cannot be known until all needs have been processed, and it is resolved during post-processing.
This is problematic for (a) user readability, (b) improving processing performance and issue feedback
This PR slightly modifies the argument processing to allow for two "explicit" formats:
- `<ID>`, if the argument is enclosed in `<>` it is always processed as a single ID
- `"filter string"`, if the argument is enclosed in `""` it is always processed as a filter string
If the string is not enclosed, then the logic is relatively similar to the existing:
- `ID`, if the argument is a single word (no spaces) then it is processed as a single ID
- otherwise, it is processed as a filter string …
> ♻️ Make `needextend` argument declarative

- sphinx_needs/defaults.py
These are post-processed internal fields, and so the directive options do not make sense and are in fact not used
> 🔧 Remove `constraints_passed`/`constraints_results` directive options

- docs/directives/needextend.rst
- docs/filter.rst
- sphinx_needs/filter_common.py
> ✨ Extend `c.this_doc()` to all directives with `filter` option

- docs/dynamic_functions.rst
- sphinx_needs/data.py
- sphinx_needs/functions/functions.py
It is unintended and unlikely the dynamic functions would have been used in there fields, but just in case we issue a warning of the deprecation, so that we can remove them in the future
fields affected: `type`, `type_name`, `type_prefix`, `type_color`, `type_style`.
this follows on from #1387 and the fields now allowed are:
- ``title``
- ``status``
- ``tags``
- ``style``
- ``constraints``
- all `needs_extra_options`
- all `needs_extra_links`
- all `needs_global_options`
---
Note, there are still maybe some outstanding questions about where dynamic functions should be processed:
- should they be processed for the need title?
- should they be processed at all for needs coming from external and/or needimport `needs.json`?
> 🔧 Deprecate use of dynamic functions in need type fields

- docs/configuration.rst
- sphinx_needs/data.py
- sphinx_needs/needs.py
Similar to #1388 for `needs_variant_options`
> 🔧 Centralise allowed variant core need fields

- sphinx_needs/functions/functions.py
- tests/__snapshots__/test_dynamic_functions.ambr
- tests/doc_test/doc_dynamic_functions/conf.py
- tests/doc_test/doc_dynamic_functions/index.rst
- tests/test_dynamic_functions.py
Currently, for an item in a list field, with a dynamic function plus other text, the other text will be silently omitted, e.g.
```restructuredtext
.. spec:: TEST_1
:id: TEST_1
:tags: test_1a;test_1b;[[copy('title')]]omitted
```
A warning is now emitted about this
> 🐛 Warn on dynamic function with surrounding text

- sphinx_needs/data.py
- tests/test_global_options.py
Even though these template are an awful design decision in sphinx-needs (hint, you don't jinja when you have a fully expressive restructuredtext syntax), let's add them back in for now for back-compatibility
closes #1420
> 🔧 Allow pre/post template `global_options`

- pyproject.toml
- tests/benchmarks/test_official.py
The memray dependency is only available for linux and macos.
> 🔧 benchmark group non win32

- docs/directives/need.rst
- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/defaults.py
- sphinx_needs/directives/need.py
- sphinx_needs/needs.py
- tests/__snapshots__/test_global_options.ambr
- tests/doc_test/doc_global_options/conf.py
- tests/doc_test/doc_global_options/index.rst
- tests/test_global_options.py
`needs_global_options`, a.k.a need field defaults, should only be used if the user does not specifically set their value,
i.e. user specified values should take precedence over defaults.
The problem with the existing logic, was that the only check for if a value had been set, was if it was "truthy".
This does not work if the user wants to explicitly set a `False` value, e.g.
```restructuredtext
.. spec:: Specification 3
:id: SPEC_3
:collapse: false
```
For `collapse` and `hide`, this is now accounted for, and so they can be allowed as defaults.
(In future this logic maybe should be extended to all fields, accounting for explicitly set empty strings and lists)
> Allow `collapse` and `hide` in `needs_global_options`

- docs/filter.rst
- docs/roles.rst
This fixes the docs build warnings emitted by RST highlighting:
```
<unknown>:1: SyntaxWarning: invalid escape sequence '\.'
<string>:1: SyntaxWarning: invalid escape sequence '\.'
<unknown>:1: SyntaxWarning: invalid escape sequence '\w'
<string>:1: SyntaxWarning: invalid escape sequence '\w'
```
Not sure about the solution though, could also be the `need-example` directive has a bug.
> 📚 Fix escape sequences

- docs/conf.py
- sphinx_needs/api/need.py
- sphinx_needs/config.py
- sphinx_needs/services/manager.py
This is an issue, because all need fields (internal and custom user ones) are stored / serialized in a "flat" dictionary, and so they cannot overlap.
Previously there was no check in place to disallow the API from doing this
> ‼️ Disallow `add_extra_option` overriding an internal field

- docs/configuration.rst
- sphinx_needs/api/need.py
- sphinx_needs/directives/need.py
- sphinx_needs/filter_common.py
- tests/__snapshots__/test_add_sections_sigs.ambr
- tests/__snapshots__/test_basic_doc.ambr
- tests/__snapshots__/test_dynamic_functions.ambr
- tests/__snapshots__/test_external.ambr
- tests/__snapshots__/test_extra_options.ambr
- tests/__snapshots__/test_list2need.ambr
- tests/__snapshots__/test_need_constraints.ambr
- tests/__snapshots__/test_need_parts.ambr
- tests/__snapshots__/test_needextend.ambr
- tests/__snapshots__/test_needimport.ambr
- tests/__snapshots__/test_needs_builder.ambr
- tests/__snapshots__/test_needs_from_toml.ambr
- tests/__snapshots__/test_needs_id_builder.ambr
- tests/__snapshots__/test_needuml.ambr
Previously defaults would be applied to any fields of a need with a "falsy" value, e.g. `None`, `False`, `0` , `""`, `[]`. ...
This is an issue, if the user wants to specifically set fields to these values, without them being overridden by defaults. Therefore, now defaults are only applied to fields with a missing or `None` value.
In the need directive context, this means that defaults will only be set for fields not specifically set in the directive options.
In the external/import need context, defaults will only be applied to missing keys in the `needs.json`, or fields with the value set to `null`.
For predicate defaults, the context passed to the expression has been restricted to a subset of fields, and these values are no longer mutated by previous defaults, i.e. each predicate gets …
> ‼️ Improve needs default field application (via needs_global_options)

- docs/tutorial.rst
I believe it needs to be `needs_extra_links` (https://sphinx-needs.readthedocs.io/en/latest/configuration.html#needs-extra-links)
> 📚 Fix needs_extra_links name

- docs/api.rst
- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/need_item.py
- tests/__snapshots__/test_basic_doc.ambr
- tests/__snapshots__/test_dynamic_functions.ambr
- tests/__snapshots__/test_external.ambr
- tests/__snapshots__/test_extra_options.ambr
- tests/__snapshots__/test_need_constraints.ambr
- tests/__snapshots__/test_needextend.ambr
- tests/__snapshots__/test_needimport.ambr
- tests/__snapshots__/test_needs_builder.ambr
- tests/__snapshots__/test_service_github.ambr
- tests/test_data.py
- tests/test_filter.py
- tests/test_need_item_api.py
Add `NeedsContent` construct, to store all data to do with content generation: `doctype`, `content`, `pre_content`, `post_content`, `jinja_content`, `template`, `pre_template`, `post_template`
These are all immutable, after the content has been initially set
note, this is part of the rationalisation of internal need fields:
> 🔧 Improve storage of content generation on `NeedItem`

- sphinx_needs/external_needs.py
Changes for [issue #1476](https://github.com/useblocks/sphinx-needs/issues/1476):
When a warning is triggered due to unknown keys in external sources, it includes the URL of the source. If the URL contains basic authentication details, those credentials will be exposed in the warning message.
FIX is simply to use the existing "clean_log" method to obfuscate the url
> 🐛 Avoid leaking auth credentials for ext. need warnings

- docs/configuration.rst
- docs/directives/need.rst
- sphinx_needs/functions/functions.py
- tests/__snapshots__/test_variants.ambr
- tests/doc_test/variant_doc/index.rst
- tests/doc_test/variant_options/conf.py
- tests/doc_test/variant_options/index.rst
- tests/test_variants.py
Instead of passing Sphinx tags directly into the context variable scope for filter strings, a new variable `build_tags` is injected which is a `set[str]`.
This avoids namespace clutter and also `NameError`s when checking for tags.
For now, this is only available for variants. Need to discuss whether to apply this to all filter strings.
> 🐛 Inject build_tags to variant filter strings

- sphinx_needs/schema/core.py
- tests/schema/__snapshots__/test_schema.ambr
- tests/schema/fixtures/reporting.yml
- tests/schema/test_schema.py
This fixes the reported rule severity set in [schema rule definitions](https://sphinx-needs.readthedocs.io/en/latest/schema/index.html#severity-levels).
The filtering for severity based on rule severity and the [needs_schema_severity](https://sphinx-needs.readthedocs.io/en/latest/configuration.html#needs-schema-severity) (minimum report severity) actually did work, but the reported severity was not set correctly.
> 🐛 Fix schema rule severity
