useblocks/sphinx-needs

- sphinxcontrib/needs/builder.py
- sphinxcontrib/needs/needs.py
- sphinxcontrib/needs/roles/need_outgoing.py
- sphinxcontrib/needs/roles/need_ref.py
- sphinxcontrib/needs/utils.py
- tests/test_official_doc.py
- tests/test_styles/test_style_blank.py
- tests/test_styles/test_style_custom.py
- tests/test_styles/test_style_modern.py
- tests/test_styles/test_style_unknown.py
This should resolve the logging issue I reported in #50.
> Issue 50 inconsistent logging import

- sphinxcontrib/needs/css/common.css
the following code snippet appears twice in this file. I've removed one copy.
> fix copy-paste duplication in common.css

- sphinxcontrib/needs/directives/needgantt.py
closes #179
is this the logic that was intended here?
> fix boolean logic

- sphinxcontrib/needs/layout.py
> fix logic bug

- docs/directives/needtable.rst
- sphinxcontrib/needs/directives/needtable.py
> needtable default sort to id_complete

- docs/configuration.rst
> Docs for nested PlantUML elements.

- AUTHORS
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/builder.py
- sphinxcontrib/needs/diagrams_common.py
- sphinxcontrib/needs/directives/need.py
- sphinxcontrib/needs/directives/needflow.py
- sphinxcontrib/needs/directives/needgantt.py
- sphinxcontrib/needs/directives/needpie.py
- sphinxcontrib/needs/directives/needsequence.py
- sphinxcontrib/needs/directives/needservice.py
- sphinxcontrib/needs/logging.py
- sphinxcontrib/needs/needs.py
- sphinxcontrib/needs/roles/need_count.py
- sphinxcontrib/needs/roles/need_outgoing.py
- sphinxcontrib/needs/roles/need_part.py
- sphinxcontrib/needs/roles/need_ref.py
- sphinxcontrib/needs/services/base.py
- sphinxcontrib/needs/services/manager.py
- sphinxcontrib/needs/utils.py
- sphinxcontrib/needs/warnings.py
- tests/test_broken_links.py
The import logic for the logging is slightly complex and causes false positives for linters.
This pull request consolidates this import logic so it only occurs in *one place*
> Consolidate logging

- sphinxcontrib/needs/services/github.py
> Changed github service max_amount default to -1 instead of 5

- sphinxcontrib/needs/directives/needfilter.py
- sphinxcontrib/needs/filter_common.py
- sphinxcontrib/needs/utils.py
small refactors so far. I was hoping to ask a few questions about the API to hopefully refactor further-
> refactor filter_common

- .github/workflows/ci.yaml
- Makefile
- docs/_static/custom.css
- docs/changelog.rst
- docs/conf.py
- docs/contributing.rst
- docs/directives/needpie.rst
- docs/index.rst
- docs/requirements.txt
- docs/snippets.rst
- noxfile.py
* Added contribute docs
* linkcheck ci workflow
* new make target:linkcheck
> Adds make targets and ci linkcheck

- docs/changelog.rst
- sphinxcontrib/needs/services/github.py
> Checks github url for ending /

- sphinxcontrib/needs/directives/needflow.py
> needflow shows all links types by default (again)

- docs/changelog.rst
- sphinxcontrib/needs/environment.py
- tests/test_official_doc.py
> Bugfix for copying static files

- docs/changelog.rst
- docs/services/github.rst
- sphinxcontrib/needs/layout.py
> Bugfix: Link function setting correct text values

- docs/configuration.rst
> Docs update for warnings

- docs/changelog.rst
- sphinxcontrib/needs/diagrams_common.py
- sphinxcontrib/needs/directives/needflow.py
- tests/doc_test/doc_needflow/index.rst
- tests/doc_test/doc_needflow/page.rst
> Fix: links for needparts get correctly calculated

- docs/changelog.rst
- sphinxcontrib/needs/css/common.css
> RTD theme fix for sphinx needs tables

- docs/changelog.rst
- docs/directives/needtable.rst
- sphinxcontrib/needs/libs/html/datatables_loader.js
> Shows horizontal scollbar for needtable

- docs/changelog.rst
- docs/dynamic_functions.rst
- docs/roles.rst
- sphinxcontrib/needs/functions/__init__.py
- sphinxcontrib/needs/functions/common.py
- sphinxcontrib/needs/needs.py
- sphinxcontrib/needs/roles/need_func.py
> Introducing need_func

- docs/conf.py
- docs/directives/needtable.rst
- sphinxcontrib/needs/css/common.css
- sphinxcontrib/needs/libs/html/datatables_loader.js
> RTD Tables: Removes space around head and content

- docs/changelog.rst
- docs/conf.py
- docs/configuration.rst
- docs/directives/needtable.rst
- sphinxcontrib/needs/css/common.css
- sphinxcontrib/needs/directives/need.py
- sphinxcontrib/needs/needs.py
- sphinxcontrib/needs/roles/need_outgoing.py
- tests/doc_test/doc_extra_links/conf.py
- tests/doc_test/doc_extra_links/index.rst
- tests/test_extra_links.py
> Adds "allow_dead_links" to "needs_extra_links"

- docs/changelog.rst
- pyproject.toml
- sphinxcontrib/needs/functions/functions.py
- sphinxcontrib/needs/needs.py
* NEEDS_FUNCTIONS gets not cleaned, as it may have already content
* Log message instead of Exception, if function is reregistered
Fixes #288
> Fix for Dyncamic function registration

- sphinxcontrib/needs/environment.py
> Deactivates copy of static for needs builder

- docs/changelog.rst
- docs/directives/needimport.rst
- sphinxcontrib/needs/directives/needimport.py
- tests/doc_test/import_doc/index.rst
- tests/test_import.py
> Fixes hide and collapse for needimport

- docs/changelog.rst
- docs/directives/needtable.rst
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/defaults.py
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/directives/utils.py
- tests/doc_test/doc_needtable/test_titles.rst
- tests/test_needtable.py
> Allows custom needtable column titles

- sphinxcontrib/needs/directives/needpie.py
> Fix: Needpie absolute amount for cake piece

- sphinxcontrib/needs/directives/needextend.py
> needextend: Not so strict id check

- docs/changelog.rst
- docs/directives/need.rst
- sphinxcontrib/needs/defaults.py
- sphinxcontrib/needs/needs.py
> needetend does not allow internal options

- poetry.lock
- pyproject.toml
> Fix dep-spec to ^sphinx4 for ^py3.7

- docs/changelog.rst
- docs/roles.rst
- sphinxcontrib/needs/directives/needtable.py
> Fix for needtable need-parts

- docs/directives/needextend.rst
- sphinxcontrib/needs/directives/needextend.py
- tests/doc_test/doc_needextend/index.rst
- tests/test_needextend.py
> Fix for whitespace handling in link lists

- sphinxcontrib/needs/needs.py
E.g. https://github.com/useblocks/sphinx-needs-codebeamer
> Service update for external sphinx-needs extensions

- docs/changelog.rst
- docs/directives/needtable.rst
- sphinxcontrib/needs/directives/needtable.py
- tests/doc_test/doc_needtable/index.rst
- tests/test_needtable.py
> Added caption for needtable

- Makefile
- docs/api.rst
- docs/changelog.rst
- docs/configuration.rst
- performance/performance_test.py
- performance/project/conf.template
- performance/project/page.template
- poetry.lock
- sphinxcontrib/needs/api/configuration.py
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/config.py
- sphinxcontrib/needs/directives/need.py
- sphinxcontrib/needs/functions/functions.py
- sphinxcontrib/needs/needs.py
- sphinxcontrib/needs/nodes/__init__.py
- sphinxcontrib/needs/services/manager.py
- sphinxcontrib/needs/warnings.py
- tests/doc_test/doc_needs_warnings/conf.py
- tests/doc_test/doc_needs_warnings/index.rst
- tests/test_needs_warning.py
> Fix Inc Build

- .github/workflows/ci.yaml
- docs/configuration.rst
- noxfile.py
- sphinxcontrib/needs/defaults.py
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/needs.py
- tests/test_needtable.py
Works only, if https://github.com/bashtage/sphinx-material/pull/120 gets merged to Sphinx-Material
Fixes #306
> Adds specific handling for material theme

- docs/configuration.rst
- sphinxcontrib/needs/config.py
- sphinxcontrib/needs/directives/need.py
- sphinxcontrib/needs/directives/needimport.py
- sphinxcontrib/needs/needs.py
- tests/doc_test/doc_needs_warnings/conf.py
- tests/doc_test/extra_options/conf.py
- tests/test_extra_options.py
- tests/test_needs_warning.py
> Fixes for extra_option and warning api calls

- poetry.lock
- sphinxcontrib/needs/needs.py
> Better needs_extra_options type handling

- docs/conf.py
- docs/configuration.rst
- noxfile.py
- performance/project/conf.template
- poetry.lock
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/filter_common.py
- sphinxcontrib/needs/layout.py
- sphinxcontrib/needs/needs.py
> Field links

- .pre-commit-config.yaml
- sphinxcontrib/needs/builder.py
- sphinxcontrib/needs/directives/needextend.py
- sphinxcontrib/needs/directives/needimport.py
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/layout.py
- sphinxcontrib/needs/roles/need_incoming.py
- sphinxcontrib/needs/roles/need_outgoing.py
- sphinxcontrib/needs/warnings.py
> lint with flake8-bugbear

- docs/_static/custom.css
- docs/changelog.rst
- docs/directives/needtable.rst
- sphinxcontrib/needs/css/common.css
- sphinxcontrib/needs/directives/needtable.py
- sphinxcontrib/needs/directives/utils.py
- tests/doc_test/doc_needtable/index.rst
- tests/test_needtable.py
> class attribute for needtables and css enhancement

- docs/changelog.rst
- sphinxcontrib/needs/directives/needgantt.py
> Fixed format string to be as defined in 1989 C standard

- sphinxcontrib/needs/directives/needpie.py
> fix for missing needpie legend

- sphinxcontrib/needs/directives/needpie.py
> close the figures, to free memory

- sphinxcontrib/needs/diagrams_common.py
- sphinxcontrib/needs/directives/needflow.py
- sphinxcontrib/needs/directives/needgantt.py
- sphinxcontrib/needs/directives/needlist.py
- sphinxcontrib/needs/roles/need_incoming.py
- sphinxcontrib/needs/roles/need_outgoing.py
- sphinxcontrib/needs/utils.py
- tests/doc_test/doc_needs_external_needs/conf.py
- tests/doc_test/doc_needs_external_needs/index.rst
- tests/doc_test/doc_needs_external_needs/needs_test_small.json
- tests/doc_test/doc_needs_external_needs/subfolder_a/index.rst
- tests/doc_test/doc_needs_external_needs/subfolder_b/subfolder_c/index.rst
- tests/test_needs_external_needs_build.py
> Adapted needlist for base_url rel path

- docs/changelog.rst
- sphinxcontrib/needs/layout.py
- tests/doc_test/doc_layout/conf.py
- tests/doc_test/doc_layout/index.rst
- tests/test_layouts.py
> Added Impl for simple_footer

- sphinxcontrib/needs/environment.py
- tests/test_official_doc.py
> PurePosixPath for static-file path calculations

- docs/changelog.rst
- docs/directives/needpie.rst
- sphinxcontrib/needs/directives/needpie.py
- sphinxcontrib/needs/filter_common.py
- sphinxcontrib/needs/utils.py
- tests/doc_test/doc_needs_filter_data/filter_code.rst
- tests/doc_test/doc_needs_filter_data/filter_code_func.py
- tests/test_needs_filter_data.py
> Support filter_func for  needpie

- .flake8
- .gitignore
- docs/changelog.rst
- sphinxcontrib/needs/builder.py
- sphinxcontrib/needs/directives/needpie.py
- sphinxcontrib/needs/needsfile.py
> Needs incremental support

- AUTHORS
- docs/changelog.rst
- sphinxcontrib/needs/directives/needbar.py
- sphinxcontrib/needs/directives/needpie.py
Fix sphinx-needs generating a needpie image in source folder
#413
> Issue-413 Fix generating needpie and needbar images in source folder

- docs/changelog.rst
- poetry.lock
- pyproject.toml
- sphinxcontrib/needs/roles/need_ref.py
- tests/doc_test/external_doc/index.rst
- tests/test_external.py
> Fix for externalneeds in need-ref

- docs/changelog.rst
- sphinxcontrib/needs/environment.py
- tests/test_styles/test_style_css_js_registration.py
> Fixes buggy file registration

- docs/changelog.rst
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/directives/needbar.py
- sphinxcontrib/needs/directives/needextract.py
- sphinxcontrib/needs/directives/needflow.py
- sphinxcontrib/needs/directives/needgantt.py
- sphinxcontrib/needs/directives/needlist.py
- sphinxcontrib/needs/directives/needpie.py
- sphinxcontrib/needs/directives/needsequence.py
- sphinxcontrib/needs/directives/needtable.py
> Add lineno to node

- .flake8
- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- docs/changelog.rst
- poetry.lock
- pyproject.toml
- sphinxcontrib/needs/api/need.py
- sphinxcontrib/needs/directives/needbar.py
- sphinxcontrib/needs/directives/needpie.py
> Bugfix: Adds need_parts to needpie/bar filter base

- .github/workflows/docker.yaml
- AUTHORS
- LICENSE
- docker/Dockerfile
- docker/build_docker.sh
- docs/changelog.rst
- docs/docker.rst
- docs/installation.rst
Implements #531 
- Dockerfile
- Script for local build
- Pipeline update for Docker
- Documentation changes
> Add Support for Docker

- pyproject.toml
- sphinxcontrib/needs/environment.py
- sphinxcontrib/needs/logging.py
remove 'sphinx<1.6` import guards
> remove sphinx <= 1.6 compat

- .flake8
- sphinx_needs/__init__.py
- sphinx_needs/api/__init__.py
- sphinx_needs/defaults.py
- sphinx_needs/filter_common.py
- sphinx_needs/functions/__init__.py
- sphinx_needs/functions/common.py
- sphinx_needs/warnings.py
- tests/data/service_github.py
Fixes done by https://github.com/useblocks/sphinxcontrib-needs/pull/566.
This PR only rebased the original PR.
> Flake8 fixes

- docs/_static/custom.css
> Fix dataTables style

- docs/changelog.rst
- docs/directives/needbar.rst
- sphinx_needs/directives/needbar.py
> Added bar label rotation parameter to needbar.

- sphinx_needs/api/configuration.py
- sphinx_needs/api/exceptions.py
- sphinx_needs/api/need.py
- sphinx_needs/builder.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/filter_common.py
- sphinx_needs/lsp/needs_store.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_ref.py
- sphinx_needs/services/manager.py
- sphinx_needs/warnings.py
- tests/conftest.py
- tests/test_github_issues.py
- tests/test_needtable.py
- tests/test_parallel_execution.py
- tests/test_test_doc.py
removing dead code.
I'm abusing the CI to test this incrementally as i strip code out
> remove some potentially unused objects

- Makefile
- docs/_static/custom.css
- docs/requirements.txt
- sphinx_needs/api/need.py
- sphinx_needs/builder.py
- sphinx_needs/directives/needreport.py
- sphinx_needs/external_needs.py
- sphinx_needs/lsp/esbonio.py
- sphinx_needs/services/open_needs.py
> Replace `confdir` with `srcdir` where appropriate.

- docs/_static/custom.css
- docs/services/open_needs.rst
- sphinx_needs/css/dark/layouts.css
- sphinx_needs/css/modern/layouts.css
- sphinx_needs/layout.py
> Better UX for the debug-layout of needs. 

- docs/directives/need.rst
- sphinx_needs/api/need.py
- sphinx_needs/defaults.py
- sphinx_needs/directives/need.py
- tests/doc_test/doc_need_delete/Makefile
- tests/doc_test/doc_need_delete/conf.py
- tests/doc_test/doc_need_delete/index.rst
- tests/doc_test/doc_need_delete/make.bat
- tests/test_lsp/test_lsp.py
- tests/test_need_delete_option.py
Added documentation and test case for need objects `:delete:` option. Fix for issue #316.
> Feature: delete option for needs

- docs/configuration.rst
- docs/directives/needreport.rst
- sphinx_needs/directives/needreport.py
- sphinx_needs/directives/needreport_template.rst
- sphinx_needs/directives/utils.py
- sphinx_needs/functions/functions.py
> Improved `needreport` directive by adding needs metrics analysis.

- docs/changelog.rst
- docs/configuration.rst
- sphinx_needs/lsp/esbonio.py
- sphinx_needs/needs.py
- tests/test_lsp/doc_lsp_custom_directive_snippets/Makefile
- tests/test_lsp/doc_lsp_custom_directive_snippets/conf.py
- tests/test_lsp/doc_lsp_custom_directive_snippets/index.rst
- tests/test_lsp/doc_lsp_custom_directive_snippets/make.bat
- tests/test_lsp/test_lsp_custom_directive_snippets.py
> Support custom directive snippets for IDE features

- docs/changelog.rst
- sphinx_needs/external_needs.py
- sphinx_needs/functions/functions.py
- sphinx_needs/utils.py
> Improvement to variants for need options.

- .pre-commit-config.yaml
- docker/Dockerfile
- docs/changelog.rst
> updated dockerfile install URLs

- docs/directives/needextract.rst
- docs/index.rst
- sphinx_needs/layout.py
- sphinx_needs/libs/html/sphinx_needs_collapse.js
> Fixed bug to improve support for many Sphinx themes.

- sphinx_needs/directives/need.py
- sphinx_needs/roles/need_incoming.py
- sphinx_needs/roles/need_outgoing.py
- tests/doc_test/variant_doc/conf.py
- tests/doc_test/variant_doc/index.rst
- tests/test_variants.py
Fix issues identified in the need option variant handling feature.
> Variant options fix

- .github/workflows/docs.yaml
- docs/changelog.rst
- docs/directives/needextract.rst
- sphinx_needs/directives/needextract.py
- tests/doc_test/doc_needextract/index.rst
> support filter argument for needextract

- docs/directives/needextract.rst
- sphinx_needs/layout.py
- sphinx_needs/libs/html/sphinx_needs_collapse.js
> Fixed rendering issues for collapse/expand button.

- docs/changelog.rst
- sphinx_needs/libs/html/sphinx_needs_collapse.js
> Fixed rendering issue with the debug layout

- docs/configuration.rst
> needs_render_context doc update

- docs/changelog.rst
- sphinx_needs/directives/needuml.py
- tests/doc_test/doc_needarch_jinja_func_import/index.rst
- tests/test_needarch.py
> fix import function to work with new flow function

- docs/changelog.rst
- sphinx_needs/directives/need.py
- sphinx_needs/needs.py
> check_links() gets called only once now

- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needimport.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needreport.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needservice.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/directives/needuml.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_count.py
- sphinx_needs/roles/need_func.py
- sphinx_needs/roles/need_incoming.py
- sphinx_needs/roles/need_outgoing.py
- sphinx_needs/roles/need_part.py
- sphinx_needs/roles/need_ref.py
- sphinx_needs/utils.py
Performance fix, provides ~5-15% less build time.
Fixes #751
> Better findall / doctree-resolved handling

- .gitignore
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/needs.py
> add_section gets called only once

- docs/changelog.rst
> updated palntuml in test folder to same version as in docs folder

- docs/changelog.rst
- docs/configuration.rst
> Improve docu for needs_extra_links to configure color and orientation

- docs/changelog.rst
- sphinx_needs/functions/functions.py
- tests/doc_test/variant_options/Makefile
- tests/doc_test/variant_options/conf.py
- tests/doc_test/variant_options/index.rst
- tests/doc_test/variant_options/make.bat
- tests/test_variants.py
This PR is the fix for issue #776.
> Fixed issue with needs_variant_options #776.

- README.rst
- docs/changelog.rst
- docs/configuration.rst
- docs/contributing.rst
- docs/installation.rst
- pyproject.toml
- sphinx_needs/css/common.css
- sphinx_needs/layout.py
- sphinx_needs/libs/html/sphinx_needs_collapse.js
Fix issues #758 and #726.
Tasks include:
- Updated package information in README.rst and PyPI site.
- Updated some text in docs.
- Updated some CSS and JS for the collapse button.
> README and PyPI site has old installation instructions

- docs/changelog.rst
- sphinx_needs/external_needs.py
- sphinx_needs/utils.py
- tests/test_clean_log.py
> Obfuscate credentials when using HTTP auth

- .gitignore
- docs/changelog.rst
- sphinx_needs/api/need.py
- sphinx_needs/diagrams_common.py
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needbar.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/directives/needextract.py
- sphinx_needs/directives/needfilter.py
- sphinx_needs/directives/needflow.py
- sphinx_needs/directives/needgantt.py
- sphinx_needs/directives/needlist.py
- sphinx_needs/directives/needpie.py
- sphinx_needs/directives/needsequence.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/directives/needuml.py
- sphinx_needs/filter_common.py
- sphinx_needs/functions/functions.py
- sphinx_needs/layout.py
- sphinx_needs/needs.py
- sphinx_needs/roles/need_incoming.py
- sphinx_needs/utils.py
- tests/test_needextract.py
**Work in progress**
Fixes #790
This PR contains all changes for #790.
It gets updated step by step, as each little change can have a dramatic impact on tests and co.
> Doctree perf

- poetry.lock
- pyproject.toml
> raising beeded matplotlib version to >= 3.3.0

- docs/changelog.rst
- sphinx_needs/directives/needextend.py
- sphinx_needs/filter_common.py
- tests/doc_test/doc_needextend_strict/index.rst
> Bugfix for needextend throwing the same error 3 times in a single warning

- docs/changelog.rst
- sphinx_needs/directives/needflow.py
- tests/doc_test/doc_needflow/conf.py
- tests/doc_test/doc_needflow/index.rst
- tests/doc_test/doc_needflow_incl_child_needs/conf.py
- tests/doc_test/doc_needflow_incl_child_needs/index.rst
- tests/test_needflow.py
> Fix: 799 needflow: nested needs on same level throws PlantUML error

- docs/changelog.rst
I just notice the entry was not merged in the right place. Fixing it.
> fix changelog entry for ref in needuml

- docs/changelog.rst
- sphinx_needs/directives/needextract.py
- sphinx_needs/layout.py
- tests/doc_test/doc_needextract/check_need_refs.rst
- tests/doc_test/doc_needextract/conf.py
- tests/doc_test/doc_needextract/index.rst
- tests/test_needextract.py
> Bugfix for Sustitutions in needextracts

- tests/doc_test/parallel_doc/conf.py
- tests/doc_test/parallel_doc/index.rst
- tests/doc_test/parallel_doc/page_3.rst
- tests/doc_test/parallel_doc/page_4.rst
- tests/test_parallel_execution.py
> Updated test cases for parallel build. (#798)

- poetry.lock
- pyproject.toml
> Allowing newer versions of jsonschema

- docs/_static/custom.css
- docs/changelog.rst
- docs/conf.py
- docs/configuration.rst
- docs/directives/needgantt.rst
- docs/directives/needimport.rst
- docs/directives/needlist.rst
- docs/directives/needsequence.rst
- docs/directives/needtable.rst
- docs/directives/needuml.rst
- docs/examples/index.rst
- docs/filter.rst
- docs/needs_templates/report_template.need
- docs/services/open_needs.rst
- sphinx_needs/directives/needreport_template.rst
- sphinx_needs/layout.py
- Included the img_class as a parameter of the `image()` function under layout.py
- Updated the collapsible containers to dropdown containers
- Minor CSS changes
> Updated the collapsible containers and minor changes

- docs/conf.py
To add links in the API documentation and remove build warnings
> 📚 DOCS: Add intersphinx

- .github/workflows/benchmark.yaml
Oops, broke the benchmark CI in #1056, this should fix it
> 🔧 Fix benchmark.yaml CI regression

- poetry.lock
- pyproject.toml
The new pydantic version currently breaks sphinx-immaterial: https://github.com/jbms/sphinx-immaterial/issues/302
> 📚 Pin pydantic version

- docs/conf.py
- docs/configuration.rst
- docs/directives/need.rst
- docs/directives/needarch.rst
- docs/directives/needuml.rst
- docs/layout_styles.rst
- docs/roles.rst
- docs/services/open_needs.rst
It has no benefit and causes issues with raw jinja and latex builds
> 📚 DOCS remove jinja templating

- sphinx_needs/data.py
- tests/__snapshots__/test_basic_doc.ambr
- tests/__snapshots__/test_export_id.ambr
- tests/__snapshots__/test_external.ambr
- tests/__snapshots__/test_import.ambr
- tests/__snapshots__/test_need_constraints.ambr
- tests/__snapshots__/test_needextend.ambr
- tests/__snapshots__/test_needs_builder.ambr
- tests/__snapshots__/test_service_github.ambr
- tests/test_data.py
To be overly cautious and guard against future changes
> 🧪 Add test to ensure need field jsonschemas are correct

- .github/workflows/ci.yaml
- pyproject.toml
- sphinx_needs/directives/need.py
- sphinx_needs/functions/functions.py
- tests/test_needs_warning.py
- tests/test_proper_warning.py
- tests/test_service_github.py
Also update dependencies:
- requests: `^2.25.1` -> `^2.32`
- requests-file: `^1.5.1` -> `^2.1`
- sphinx-data-viewer: `^0.1.1` -> `^0.1.5`
> ⬆️ Drop sphinx 5, support sphinx 8

- docs/api.rst
- docs/configuration.rst
- docs/dynamic_functions.rst
- sphinx_needs/directives/need.py
- sphinx_needs/directives/needtable.py
- sphinx_needs/functions/__init__.py
- sphinx_needs/functions/common.py
- sphinx_needs/functions/functions.py
- sphinx_needs/roles/need_func.py
- tests/doc_test/doc_df_user_functions/conf.py
- tests/doc_test/doc_df_user_functions/index.rst
- tests/test_dynamic_functions.py
- strictly type functions
- fix issue with wrong type to `str.replace`
- log warning, if incorrect function or return type, rather than excepting (with correct source location)
- add test for warnings
- add `DynamicFunction` protocol to API documentation
> 🔧 Improve typing/docs of `DynamicFunction`

- sphinx_needs/roles/need_part.py
- tests/__snapshots__/test_need_parts.ambr
- tests/doc_test/doc_need_parts/conf.py
- tests/doc_test/doc_need_parts/index.rst
- tests/test_need_parts.py
parts should be assigned to the "closest" parent need
fixes #802
> 🐛 fix parts defined in nested needs

- sphinx_needs/warnings.py
> 👌 early exit from `process_warnings` if no warnings

- sphinx_needs/roles/need_part.py
- tests/__snapshots__/test_need_parts.ambr
- tests/doc_test/doc_need_parts/index.rst
> 🐛 Fix `need_part` with multi-line content

- sphinx_needs/directives/needreport.py
- sphinx_needs/directives/needreport_template.rst
- sphinx_needs/directives/utils.py
- tests/test_needreport.py
these need to be post-processed
fixes #1110
> 🐛 Fix `needreport` `usage` numbers

- sphinx_needs/builder.py
- sphinx_needs/needsfile.json
- sphinx_needs/needsfile.py
- tests/__snapshots__/test_basic_doc.ambr
- tests/__snapshots__/test_external.ambr
- tests/__snapshots__/test_need_constraints.ambr
- tests/__snapshots__/test_needextend.ambr
- tests/__snapshots__/test_needimport.ambr
- tests/__snapshots__/test_needs_builder.ambr
- tests/__snapshots__/test_needs_id_builder.ambr
- tests/__snapshots__/test_service_github.ambr
- tests/test_basic_doc.py
- tests/test_external.py
- tests/test_need_constraints.py
- tests/test_needextend.py
- tests/test_needimport.py
- tests/test_needs_builder.py
- tests/test_needs_id_builder.py
- tests/test_service_github.py
To record that the `needs.json` was created by `sphinx_needs` and also the version that created it.
> 👌 Add `creator` key to `needs.json`

- sphinx_needs/data.py
- sphinx_needs/needs.py
See https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata
> 🔧 Set `env_version` for sphinx extension

- sphinx_needs/roles/need_count.py
- tests/doc_test/doc_need_count/index.rst
- tests/test_need_count.py
> 🐛 FIX `need_count` infinite ratio

- .github/workflows/docker.yaml
- docs/changelog.rst
- pyproject.toml
- sphinx_needs/needs.py
See: https://sphinx-needs--1326.org.readthedocs.build/en/1326/changelog.html
> 🚀 Release v4.0.0

- docs/api.rst
- sphinx_needs/api/need.py
- sphinx_needs/data.py
- sphinx_needs/directives/needextend.py
- sphinx_needs/need_item.py
- tests/test_filter.py
- tests/test_need_item_api.py
We can now record more information about the `needextend` location
> 👌 Capture more information about modifications on `NeedItem`
